# Generated by Django 3.2.5 on 2021-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
