# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UberEats-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UberEats-Clone
  pod 'Stripe', '21.7.0'
  pod 'lottie-ios', '3.2.3'
  pod 'FBSDKCoreKit', '11.0.1'
  pod 'FBSDKLoginKit', '11.0.1'
  pod 'FBSDKShareKit', '11.0.1'
  pod 'Alamofire', '5.4.3'
  pod 'SwiftyJSON', '5.0.1'
  pod 'SkeletonView', '1.21.1'
  pod 'DropDown', '2.3.13'
  pod 'Charts', '3.6.0'
  
  
  target 'UberEats-CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UberEats-CloneUITests' do
    # Pods for testing
  end

end
